"""init

Revision ID: 935180fe1630
Revises: 
Create Date: 2022-03-12 18:04:01.782589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '935180fe1630'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prediction',
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('filename_id', sa.String(), nullable=False),
    sa.Column('result', sa.String(), nullable=False),
    sa.Column('probability_VI0', sa.Float(), nullable=False),
    sa.Column('probability_VI1', sa.Float(), nullable=False),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('heatmap_name', sa.String(), nullable=True),
    sa.Column('heatmap_name_id', sa.String(), nullable=True),
    sa.Column('timestamp', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('filename_id', 'model_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prediction')
    op.drop_table('image')
    # ### end Alembic commands ###
